Reference cycles in Python
++++++++++++++++++++++++++

Exception traceback
===================

Exception.__traceback__

Reference leak: XXX

asyncio Future
==============

Future.set_exception()

concurrent.futures WorkItem
===========================

https://bugs.python.org/issue31249

frame clear XXX
===============

XXXX
